version: 2.1
orbs:
  node: circleci/node@1.1.6
executors:
  language-build:
    docker:
      - image: stonezt2000/dimensons_langs
jobs:
  build-and-test:
    executor:
      name: language-build
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: sudo useradd dimensions_bot
            - run: npm install
            - run: sudo npm run test
workflows:
    build-and-test:
      jobs:
        - build-and-test
