version: 2.1
orbs:
  node: circleci/node@1.1.6
  codecov: codecov/codecov@1.0.2

executors:
  language-build:
    docker:
      - image: stonezt2000/dimensions_langs:latest
      - image: circleci/mongo:latest

jobs:
  build-and-test:
    executor:
      name: language-build
    steps:
      - checkout
      - run:
          name: install dockerize
          command: wget https://github.com/jwilder/dockerize/releases/download/$DOCKERIZE_VERSION/dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz && sudo tar -C /usr/local/bin -xzvf dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz && rm dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz
          environment:
            DOCKERIZE_VERSION: v0.3.0
      - run:
          name: Wait for db
          command: dockerize -wait tcp://localhost:27017 -timeout 1m
      - node/with-cache:
          steps:
            - run: npm install
            - run: sudo npm run test
      - run: npm run codecov
      - store_artifacts:
          path: coverage.lcov
          destination: coverage.lcov

      - codecov/upload:
          file: coverage.lcov

workflows:
    build-and-test:
      jobs:
        - build-and-test
