version: 2.1
orbs:
  node: circleci/node@1.1.6
  codecov: codecov/codecov@1.0.2

executors:
  language-build:
    docker:
      - image: stonezt2000/dimensions_langs:latest

jobs:
  build-and-test:
    executor:
      name: language-build
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm install
            - run: npm install --only=dev
            - run: sudo npm run test
      - run: npm run codecov

      - store_artifacts:
          path: coverage.lcov
          destination: coverage.lcov

      - codecov/upload:
          file: coverage.lcov

workflows:
    build-and-test:
      jobs:
        - build-and-test
