version: 2.1
orbs:
  node: circleci/node@1.1.6
  codecov: codecov/codecov@1.0.2
executors:
  language-build:
    docker:
      - image: stonezt2000/dimensions_langs:latest
jobs:
  build-and-test:
    executor:
      name: language-build
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm install
            - run: npm install --only=dev
            - run: sudo npm run test
      - codecov/upload:
        file: ./coverage/coverage-final.json
workflows:
    build-and-test:
      jobs:
        - build-and-test
