version: 2.1
orbs:
  node: circleci/node@1.1.6

executors:
  language-build:
    docker:
      - image: stonezt2000/dimensions_langs:latest

jobs:
  build-and-test:
    executor:
      name: language-build
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm install
            - run: npm install --only=dev
            - run: sudo npm run test
            - run:
              name: Sending coverage to Code Cov
              command: |
                bash <($CURL -s https://codecov.io/bash) -t $CODE_COV_TOKEN -f ./coverage/coverage-final.json

workflows:
    build-and-test:
      jobs:
        - build-and-test
