version: '2.1'

services:
  mongodb_container:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
    ports:
      - 27017-27019:27017-27019
    volumes:
      - mongodb_data_container:/data/db
volumes:
  mongodb_data_container: